# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "test_branch", "test_of_test_branch" ]
  pull_request:
    branches: [ "main", "test_branch", "test_of_test_branch" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Send email
        # You may pin to the exact commit or the version.
        # uses: dawidd6/action-send-mail@611879133a9569642c41be66f4a323286e9b8a3b
        uses: dawidd6/action-send-mail@v4
        with:
          # Connection URL protocol://user:password@server:port, protocol can be smtp or smtp+starttls, replaces server_address, server_port, secure, username and password
          # connection_url: # optional
          # # SMTP server address
          server_address: "imap.gmail.com"
          # # SMTP server port
          server_port: 993
          # # Whether this connection use TLS (default is true if server_port is 465)
          # secure: # optional
          # # Authenticate as this user to SMTP server
          # username: # optional
          # # Authenticate with this password to SMTP server
          # password: # optional
          # # Subject of mail message
          subject: "Github Actions"
          # Recipients mail addresses (separated with comma)
          to: "acain589@gmail.com"
          # Full name of mail sender (might be with an email address specified in <>)
          from: "Leroy Team"
          # Body of mail message (might be a filename prefixed with file:// to read from)
          # body: # optional
          # # HTML body of mail message (might be a filename prefixed with file:// to read from)
          # html_body: # optional
          # # Carbon copy recipients (separated with comma)
          # cc: # optional
          # # Blind carbon copy recipients (separated with comma)
          # bcc: # optional
          # # An email address that will appear on the Reply-To field
          # reply_to: # optional
          # # The Message-ID this message is replying to
          # in_reply_to: # optional
          # # Allow unsigned/invalid certificates
          # ignore_cert: # optional
          # # Convert body from Markdown to HTML (set content_type input as text/html too)
          # convert_markdown: # optional
          # # Files that will be added to mail message attachments (separated with comma)
          # attachments: # optional
          # # Set Priority level for the mail message to 'high', 'normal' (default) or 'low'
          # priority: # optional
          # # Log option for nodemailer
          # nodemailerlog: # optional
          # # Debug option for nodemailer
          # nodemailerdebug: # optional
                
